# Generated by Django 5.2.16 on 2026-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled start date and time for the class.', null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='SCHEDULED', help_text='Class status: Scheduled, Live, or Completed.', max_length=15),
        ),
    ]
