# Generated by Django 5.2.16 on 2026-10-03 15:56

import classrooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_scheduled_at_classroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, default=classrooms.models.generate_classroom_code, help_text='Unique join code for students (e.g., MATH101 or 6-char code).', max_length=10, unique=True),
        ),
    ]
