# Generated by Django 5.2.16 on 2026-10-03 16:03

import classrooms.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_classroom_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Advanced Operating Systems Lecture 4', max_length=200)),
                ('subject', models.CharField(help_text='e.g. Computer Science', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Syllabus, topics, or instructions for attendees.')),
                ('room_code', models.CharField(db_index=True, default=classrooms.models.generate_secure_room_code, help_text='Unique secure room code for participants to join.', max_length=20, unique=True)),
                ('room_password_hash', models.CharField(blank=True, help_text='Cryptographically hashed room password (never stored in plain text).', max_length=255)),
                ('scheduled_date', models.DateField(help_text='Date when class will occur.')),
                ('scheduled_time', models.TimeField(help_text='Start time of the class.')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Class duration in minutes.')),
                ('max_students', models.PositiveIntegerField(default=50, help_text='Maximum allowed student capacity.')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(help_text='Instructor hosting this live class session.', on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['-scheduled_date', '-scheduled_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('JOINED', 'Joined'), ('LEFT', 'Left'), ('DISCONNECTED', 'Disconnected'), ('KICKED', 'Kicked')], default='JOINED', max_length=20)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classrooms.liveclass')),
            ],
            options={
                'verbose_name': 'Class Participant',
                'verbose_name_plural': 'Class Participants',
                'ordering': ['-join_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='classrooms.liveclass')),
            ],
            options={
                'verbose_name': 'Class Chat Message',
                'verbose_name_plural': 'Class Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total attendance duration in minutes')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classrooms.liveclass')),
            ],
            options={
                'verbose_name': 'Live Class Attendance',
                'verbose_name_plural': 'Live Class Attendances',
                'ordering': ['student_name'],
            },
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['teacher', 'status'], name='classrooms__teacher_87a663_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='classrooms__schedul_b70ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['room_code'], name='classrooms__room_co_f43345_idx'),
        ),
        migrations.AddIndex(
            model_name='classparticipant',
            index=models.Index(fields=['live_class', 'student_email'], name='classrooms__live_cl_1bb914_idx'),
        ),
        migrations.AddIndex(
            model_name='classparticipant',
            index=models.Index(fields=['live_class', 'status'], name='classrooms__live_cl_3f6478_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['live_class', 'created_at'], name='classrooms__live_cl_17df4c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['live_class', 'student_name'], name='classrooms__live_cl_0631c3_idx'),
        ),
    ]
