# Generated by Django 5.2.16 on 2026-10-03 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_liveclass_classparticipant_chatmessage_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEFT', 'Left')], default='PRESENT', help_text='Attendance status e.g. PRESENT, ABSENT, LEFT', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Registered student account if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Registered user account if participant is logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_class_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['live_class', 'student'], name='classrooms__live_cl_8f9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='classparticipant',
            index=models.Index(fields=['live_class', 'user'], name='classrooms__live_cl_184812_idx'),
        ),
    ]
