# Generated by Django 5.2.16 on 2026-10-04 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_attendance_status_attendance_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who sent this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
