# Generated by Django 5.2.16 on 2026-10-04 03:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_chatmessage_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEFT', 'Left'), ('DISCONNECTED', 'Disconnected')], default='PRESENT', help_text='Attendance status e.g. PRESENT, ABSENT, LEFT, DISCONNECTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='classparticipant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('JOINED', 'Joined'), ('LEFT', 'Left'), ('DISCONNECTED', 'Disconnected'), ('KICKED', 'Kicked')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['live_class', 'status'], name='classrooms__live_cl_ae6960_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='classrooms__student_77be1d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['live_class', 'sender'], name='classrooms__live_cl_df4baa_idx'),
        ),
        migrations.AddIndex(
            model_name='classparticipant',
            index=models.Index(fields=['live_class', 'last_seen_at'], name='classrooms__live_cl_b6f858_idx'),
        ),
    ]
