# Generated by Django 5.2.16 on 2026-10-04 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_attendance_created_at_attendance_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='access_mode',
            field=models.CharField(choices=[('PUBLIC_LINK', 'Public Link'), ('ENROLLMENT_ONLY', 'Enrollment Only'), ('PASSWORD_PROTECTED', 'Password Protected')], db_index=True, default='PUBLIC_LINK', help_text='Class security access model (Public Link, Enrollment Only, Password Protected).', max_length=30),
        ),
        migrations.CreateModel(
            name='ClassAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('request_note', models.TextField(blank=True, help_text='Optional note from student requesting access.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('live_class', models.ForeignKey(help_text='Live class requested.', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='classrooms.liveclass')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student requesting access.', on_delete=django.db.models.deletion.CASCADE, related_name='class_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Access Request',
                'verbose_name_plural': 'Class Access Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['live_class', 'status'], name='classrooms__live_cl_d0321d_idx'), models.Index(fields=['student', 'status'], name='classrooms__student_813eb2_idx'), models.Index(fields=['status', 'created_at'], name='classrooms__status_43ce5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ENROLLED', 'Enrolled'), ('REVOKED', 'Revoked'), ('COMPLETED', 'Completed')], db_index=True, default='ENROLLED', max_length=20)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(help_text='Live class the student is enrolled in or invited to.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classrooms.liveclass')),
                ('student', models.ForeignKey(help_text='Enrolled or invited student user account.', on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['live_class', 'status'], name='classrooms__live_cl_6ca97f_idx'), models.Index(fields=['student', 'status'], name='classrooms__student_d5d2ee_idx'), models.Index(fields=['status', 'created_at'], name='classrooms__status_800393_idx')],
                'constraints': [models.UniqueConstraint(fields=('live_class', 'student'), name='unique_liveclass_student_enrollment')],
            },
        ),
    ]
