# Generated by Django 5.2.16 on 2026-10-07 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_liveclass_access_mode_classaccessrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassParticipantModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MUTED', 'Muted'), ('REMOVED', 'Removed'), ('HAND_RAISED', 'Hand Raised'), ('HAND_LOWERED', 'Hand Lowered')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Optional moderation reason.', max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='True if moderation restriction is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Live Class Moderation Event',
                'verbose_name_plural': 'Live Class Moderation Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='hand_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='is_hand_raised',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classparticipant',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='classparticipant',
            index=models.Index(fields=['live_class', 'is_hand_raised'], name='classrooms__live_cl_42c3e2_idx'),
        ),
        migrations.AddField(
            model_name='liveclassparticipantmoderation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated moderation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveclassparticipantmoderation',
            name='live_class',
            field=models.ForeignKey(help_text='Live class session.', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to='classrooms.liveclass'),
        ),
        migrations.AddField(
            model_name='liveclassparticipantmoderation',
            name='student',
            field=models.ForeignKey(help_text='Target student.', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='liveclassparticipantmoderation',
            index=models.Index(fields=['live_class', 'active'], name='classrooms__live_cl_df387b_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassparticipantmoderation',
            index=models.Index(fields=['live_class', 'student', 'action', 'active'], name='classrooms__live_cl_2e43f7_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassparticipantmoderation',
            index=models.Index(fields=['live_class', 'created_at'], name='classrooms__live_cl_60dea9_idx'),
        ),
    ]
