# Generated by Django 5.2.16 on 2026-10-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_liveclassparticipantmoderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Ended'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
