# Generated by Django 5.2.16 on 2026-10-08 03:21

import classrooms.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_alter_liveclass_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='revocation_reason',
            field=models.CharField(blank=True, help_text='Optional reason for revocation/removal.', max_length=255),
        ),
        migrations.CreateModel(
            name='ClassInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=classrooms.models.generate_invite_token, help_text='Cryptographically secure URL-safe random token.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 for unlimited uses until capacity/expiration.')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invite_tokens', to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(help_text='Live class associated with this secure invite token.', on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='classrooms.liveclass')),
            ],
            options={
                'verbose_name': 'Class Invite Token',
                'verbose_name_plural': 'Class Invite Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_revoked'], name='classrooms__token_ee285a_idx'), models.Index(fields=['live_class', 'is_revoked'], name='classrooms__live_cl_f2437b_idx')],
            },
        ),
    ]
