# Generated by Django 5.2.16 on 2026-10-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google OAuth unique subject ID (sub).', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, help_text='Google account profile photo URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
