# Generated by Django 5.2.16 on 2026-10-04 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_id_user_google_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TEACHER_ACTIVATED', 'Teacher Activated'), ('TEACHER_DEACTIVATED', 'Teacher Deactivated'), ('STUDENT_ACTIVATED', 'Student Activated'), ('STUDENT_DEACTIVATED', 'Student Deactivated'), ('CLASS_CANCELLED', 'Class Cancelled'), ('OTHER', 'Other Action')], db_index=True, default='OTHER', max_length=50)),
                ('target_type', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Administrator who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_ad_action_cf4561_idx'), models.Index(fields=['target_type', 'target_id'], name='accounts_ad_target__105f7f_idx')],
            },
        ),
    ]
