# Generated by Django 5.2.16 on 2026-10-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('TEACHER_ACTIVATED', 'Teacher Activated'), ('TEACHER_DEACTIVATED', 'Teacher Deactivated'), ('STUDENT_ACTIVATED', 'Student Activated'), ('STUDENT_DEACTIVATED', 'Student Deactivated'), ('CLASS_CREATED', 'Class Created'), ('CLASS_CANCELLED', 'Class Cancelled'), ('CLASS_RESCHEDULED', 'Class Rescheduled'), ('CLASS_STARTED', 'Class Started'), ('CLASS_ENDED', 'Class Ended'), ('ENROLLMENT_CREATED', 'Enrollment Created'), ('ENROLLMENT_REVOKED', 'Enrollment Revoked'), ('ACCESS_REQUEST_APPROVED', 'Access Request Approved'), ('ACCESS_REQUEST_REJECTED', 'Access Request Rejected'), ('CLASS_ACCESS_MODE_CHANGED', 'Class Access Mode Changed'), ('OTHER', 'Other Action')], db_index=True, default='OTHER', max_length=50),
        ),
    ]
