# Generated by Django 5.2.16 on 2026-10-04 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0007_attendance_created_at_attendance_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Target recipient email address.', max_length=254)),
                ('email_type', models.CharField(help_text='Email category (e.g. WELCOME_TEACHER, CLASS_CREATED, REMINDER).', max_length=60)),
                ('subject', models.CharField(help_text='Rendered email subject header.', max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='SENT', help_text='Delivery dispatch status.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Sanitized error summary if dispatch failed.')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when email attempt occurred.')),
                ('related_live_class', models.ForeignKey(blank=True, help_text='Associated live class session if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='classrooms.liveclass')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['status', 'sent_at'], name='notificatio_status_9f9850_idx'), models.Index(fields=['email_type', 'sent_at'], name='notificatio_email_t_3cba5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CLASS_CREATED', 'Class Created'), ('CLASS_SCHEDULED', 'Class Scheduled'), ('CLASS_STARTING', 'Class Starting Soon'), ('CLASS_STARTED', 'Class Started'), ('CLASS_ENDED', 'Class Ended'), ('CLASS_CANCELLED', 'Class Cancelled'), ('STUDENT_JOINED', 'Student Joined'), ('TEACHER_CLASS_UPDATE', 'Class Updated'), ('SYSTEM', 'System Notification')], default='SYSTEM', help_text='Category of notification.', max_length=50)),
                ('title', models.CharField(help_text='Concise summary header.', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification body content.')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Read/unread receipt flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when notification was issued.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when recipient marked as read.', null=True)),
                ('recipient', models.ForeignKey(help_text='User receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_live_class', models.ForeignKey(blank=True, help_text='Associated live class session if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='classrooms.liveclass')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx')],
            },
        ),
    ]
