# Generated by Django 5.2.16 on 2026-10-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLASS_CREATED', 'Class Created'), ('CLASS_SCHEDULED', 'Class Scheduled'), ('CLASS_STARTING', 'Class Starting Soon'), ('CLASS_STARTED', 'Class Started'), ('CLASS_ENDED', 'Class Ended'), ('CLASS_CANCELLED', 'Class Cancelled'), ('STUDENT_JOINED', 'Student Joined'), ('TEACHER_CLASS_UPDATE', 'Class Updated'), ('STUDENT_INVITED', 'Student Invited'), ('ENROLLMENT_APPROVED', 'Enrollment Approved'), ('ENROLLMENT_REJECTED', 'Enrollment Rejected'), ('ENROLLMENT_REVOKED', 'Enrollment Revoked'), ('ACCESS_REQUESTED', 'Access Requested'), ('SYSTEM', 'System Notification')], default='SYSTEM', help_text='Category of notification.', max_length=50),
        ),
    ]
